etl:
  db:
    url: ${DB_URL:"jdbc:postgresql://localhost:32878/test?loggerLevel=OFF"}
    user: "test"
    password: "test"
    cloneUrl: ${DB_URL:"jdbc:postgresql://localhost:32878/test?loggerLevel=OFF"}
    cloneUser: "test"
    clonePassword: "test"
  account: "midataextractorsbox"
  connection-string: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:52189/devstoreaccount1;"

extraction:
  max:
    batch:
      row: 1
  filter:
    jurisdiction:
      in:
      out:
        - "'AUTOTEST1'"
        - "'TEST'"
  caseTypes:
  - container: "test-container"
    caseType: "test"
    type: "jsonlines"
    prefix: "JLines"
    query: "SELECT ID, NAME FROM parent WHERE ID = 1"
  - container: "disabled-container"
    caseType: "disabled-test"
    type: "jsonlines"
    prefix: "JLines"
    disabled: true
    query: "SELECT ID, NAME FROM parent WHERE ID = 1"
