# Java
# Package your Java project.
# Add steps that install, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

trigger:
  batch: true
  branches:
    include:
      - master

  tags:
    include:
      - v*

pr:
  autoCancel: true
  branches:
    include:
      - master
      - feature/*

variables:
#  group: pipeline-env-variables
  application.name: 'data-extractor-job'
  azure.container.registry: 'ssprivate$(env).azurecr.io'
  azure.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.upper)'
  azure.aks.resourcegroup: 'ss_$(env)_kubernetes_resource_group'
  azure.aks.cluster: 'ss_aks_$(env)'
  azure.prom.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.prom.upper)'
  azure.prom.aks.resourcegroup: 'ss_$(env.prom)_kubernetes_resource_group'
  azure.prom.aks.cluster: 'ss_aks_$(env.prom)'
  manual.branch.prefix: 'master'
  product: 'mi'
  chart.env: 'preview'
  azure.prom.acr: 'ssprivate$(env.prom)'

resources:
  repositories:
    - repository: mi-core
      type: github
      name: hmcts/mi-core-lib
      endpoint: hmcts

stages:
  - template: ./pipeline-steps/build-deploy-stage.yaml 