# Java
# Package your Java project.
# Add steps that install, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

trigger:
  batch: true
  branches:
    include:
      - master

  tags:
    include:
      - v*

pr:
  autoCancel: true
  branches:
    include:
      - master
      - feature/*

variables:
#  group: pipeline-env-variables
  application.name: 'data-extractor-job'
  azure.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.upper)'
  azure.aks.resourcegroup: 'ss_$(env)_kubernetes_resource_group'
  azure.aks.cluster: 'ss_aks_$(env)'
  azure.prom.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.prom.upper)'
  azure.prom.aks.resourcegroup: 'ss_$(env.prom)_kubernetes_resource_group'
  azure.prom.aks.cluster: 'ss_aks_$(env.prom)'
  manual.branch.prefix: 'master'
  product: 'mi'
  chart.env: 'preview'
  azure.prom.acr: 'ssprivate$(env.prom)'

resources:
  repositories:
    - repository: mi-core
      type: github
      name: hmcts/mi-core-lib
      endpoint: hmcts

jobs:
  - job: EchoVariables
    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      env: 'sbox'
    steps:
      - template: ./pipeline-steps/templates/tasks/echo-variables.yaml
        parameters:
          azureContainerRegistry: $(azure.prom.acr)

  - job: BuildAndTestApplication
    pool:
      vmImage: 'Ubuntu-16.04'
    dependsOn: EchoVariables
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
      aptDependencies: 'qtbase5-dev'
    steps:
      - template: pipeline-steps/templates/build-application.yaml@mi-core
      - template: pipeline-steps/templates/publish-tests.yaml@mi-core
      - template: pipeline-steps/templates/docker-build.yaml@mi-core
        parameters:
          azureContainerRegistry: $(azure.container.registry)
          azureSubscriptionEndpoint: $(azure.subscription.endpoint)
          applicationName: $(application.name)

  - job: DeployOnTest
    dependsOn: BuildAndTestApplication
    condition:  and(succeeded(), variables['System.PullRequest.PullRequestId'])
    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      getDockerTag.DOCKER_TAG: $[ dependencies.BuildAndTestApplication.outputs['getDockerTag.DOCKER_TAG'] ]
    steps:
      - template: pipeline-steps/templates/helm-install-chart.yaml@mi-core
        parameters:
          azureContainerRegistry: $(azure.container.registry)
          azureSubscriptionEndpoint: $(azure.subscription.endpoint)
          applicationName: $(application.name)
          aksResourceGroup: $(azure.aks.resourcegroup)
          aksCluster: $(azure.aks.cluster)
          jobName: $(application.name)
          namespace: mi
          chartEnv: $(chart.env)
      - template: pipeline-steps/templates/kubernetes-wait-for-job.yaml@mi-core
        parameters:
          azureSubscriptionEndpoint: $(azure.subscription.endpoint)
          aksResourceGroup: $(azure.aks.resourcegroup)
          aksCluster: $(azure.aks.cluster)
          jobName: $(application.name)
          namespace: $(product)
          projectName: $(application.name)

  - job: DeployOnStg

    dependsOn: BuildAndTestApplication

    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      getDockerTag.DOCKER_TAG: $[ dependencies.BuildAndTestApplication.outputs['getDockerTag.DOCKER_TAG'] ]
    steps:
      - template: pipeline-steps/templates/helm-install-chart.yaml@mi-core
        parameters:
          azureContainerRegistry: $(azure.container.registry)
          azureSubscriptionEndpoint: $(azure.subscription.endpoint)
          applicationName: $(application.name)
          aksResourceGroup: $(azure.stg.aks.resourcegroup)
          aksCluster: $(azure.stg.aks.cluster)
          jobName: $(application.name)
          namespace: $(product)
          chartEnv: $(chart.env)
      - template: pipeline-steps/templates/kubernetes-wait-for-job.yaml@mi-core
        parameters:
          azureSubscriptionEndpoint: $(azure.subscription.endpoint)
          aksResourceGroup: $(azure.stg.aks.resourcegroup)
          aksCluster: $(azure.stg.aks.cluster)
          jobName: $(application.name)
          namespace: $(product)
          projectName: $(application.name)

  - job: PromoteProd
    dependsOn: DeployOnTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#    condition: succeeded()

    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      getDockerTag.DOCKER_TAG: $[ dependencies.BuildAndTestApplication.outputs['getDockerTag.DOCKER_TAG'] ]
      System.Debug: true
    steps:
      - template: ./pipeline-steps/templates/promote-build.yaml
        parameters:
          azureContainerRegistry: $(azure.container.registry)
          applicationName: $(application.name)
          azureDestinyContainerRegistry: $(azure.prom.acr)
          azureProdSubscription: $(azure.prom.subscription.endpoint)
          originAcr: $(azure.prom.acr)
