# Java
# Package your Java project.
# Add steps that install, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

trigger:
  batch: true
  branches:
    include:
      - master
      - ithc

  tags:
    include:
      - v*

pr:
  autoCancel: true
  branches:
    include:
      - master

variables:
#  group: pipeline-env-variables
  ${{ if startsWith( variables['Build.SourceBranch'], 'refs/pull/') }}:
    environment: 'test'
    env.upper: 'TEST'
  ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')) }}:
    environment: 'stg' #Uset test and promoting to stg until prod is ready
    env.upper: 'STG'
  env.prom: 'prod'
  env.prom.upper: 'PROD'
  application.name: 'data-extractor-job'
  azure.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.upper)'
  azure.aks.resourcegroup: 'ss-$(env)-00-rg'
  azure.aks.cluster: 'ss-$(env)-00-aks'
  azure.prom.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.prom.upper)'
  manual.branch.prefix: 'master'
  product: 'mi'
  vault: 'mi-vault-$(env)'
  helm.repo: 'sdshmctspublic'
  
resources:
  repositories:
    - repository: mi-core
      type: github
      name: hmcts/mi-core-lib
      endpoint: hmcts

stages:
  - template: pipeline-steps/templates/build-deploy-stage.yaml@mi-core
    parameters:
      env: $(environment)
      applicationName: $(application.name)
      product: $(product)
      azureVault: $(vault)
      chartEnv: $(environment)
      promEnv: $(env.prom)
      mutationTest: False
      functionalTest: true
      preIntegrationTest: true
      helmRepo: $(helm.repo)
      agentPool: hmcts-ss-$(environment)
      azureSecreKeys: 'ccdro-user,ccdro-password,data-extractor-connection-string'
      envMapping:
      - key: BUILD_VERSION
        value: Build.BuildId
      azureKeyMapping: 
      - key: ETL_DB_USER
        value: 'ccdro-user'
      - key: ETL_DB_PASSWORD
        value: 'ccdro-password'
      - key: ETL_CONNECTIONSTRING
        value: 'data-extractor-connection-string'
