info:
  app:
    name: ${spring.application.name}

spring:
  application:
    name: mi-data-extractor
    
etl:
  db:
    url: "jdbc:postgresql://localhost:5432/ccd_data_store?sslmode=require"
    user: "dumyUser"
    password: "cdummyPassword"
    cloneUrl: "jdbc:postgresql://localhost:5432/ccd_data_store?sslmode=require"
    cloneUser: "cloneUser"
    clonePassword: "clonePassword"
  account: "midatastgsbox"
  connection-string: "dummyConnectionString"

smoke.test.enabled: false

extraction:
  initialise: false
  max:
    batch:
      row: 100000
  filter:
    jurisdiction:
      in:
      out:
      - "'AUTOTEST1'"
      - "'TEST'"

application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:""}

task:
  SetLastUpdateMetadata: ${TASK_SET_LAST_UPDATE:false}