info:
  app:
    name: ${spring.application.name}

spring:
  application:
    name: mi-data-extractor
    
etl:
  db:
    url: "jdbc:postgresql://localhost:5432/ccd_data_store?sslmode=require"
    user: "dumyUser"
    password: "cdummyPassword"
  account: "midatastgsbox"
  connection-string: "dummyConnectionString"

extraction:
  caseTypes:
    - container: "grantofrepresentation"
      caseType: "GrantOfRepresentation"
      type: "jsonlines"
      prefix: "PROB-GOR"
    - container: "caveat"
      caseType: "Caveat"
      type: "jsonlines"
      prefix: "PROB-CAVEAT"
    - container: "willlodgement"
      caseType: "WillLodgement"
      type: "jsonlines"
      prefix: "PROB-WL"
    - container: "standingsearch"
      caseType: "StandingSearch"
      type: "jsonlines"
      prefix: "PROB-SS"
    - container: "divorce"
        caseType: "DIVORCE"
        type: "jsonlines"
        prefix: "DIV"
application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:""}