info:
  app:
    name: ${spring.application.name}
  config:
    import: optional:configtree:/mnt/secrets/*/

spring:
  application:
    name: mi-data-extractor
  main:
    allow-circular-references: true

testing:
  config: ${ccdro-user:"dumyUser"}
    
etl:
  db:
    url: "jdbc:postgresql://localhost:5432/ccd_data_store?sslmode=require"
    user: ${ccdro-user:"dumyUser"}
    password: ${ccdro-password:"cdummyPassword"}
    cloneUrl: "jdbc:postgresql://localhost:5432/ccd_data_store?sslmode=require"
    cloneUser: ${ccdro-clone-user:"cloneUser"}
    clonePassword: ${ccdro-clone-password:"clonePassword"}
  account: "midatastgsbox"
  connection-string: ${data-extractor-connection-string:"dummyConnectionString"}

smoke.test.enabled: false

extraction:
  initialise: false
  max:
    batch:
      row: 100000
  filter:
    jurisdiction:
      in:
      out:
      - "'AUTOTEST1'"
      - "'TEST'"

application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:appinsights-instrumentationkey:""}

task:
  SetLastUpdateMetadata: ${TASK_SET_LAST_UPDATE:false}
  validateBlob: ${TASK_VALIDATE_BLOB:false}
  deleteInvalidBlob: ${TASK_DELETE_INVALID_BLOB:false}