info:
  app:
    name: ${spring.application.name}

spring:
  application:
    name: mi-data-extractor
    
etl:
  db:
    url: "jdbc:postgresql://localhost:5432/ccd_data_store?sslmode=require"
    user: "dumyUser"
    password: "cdummyPassword"
  account: "midatastgsbox"
  connection-string: "dummyConnectionString"

smoke.test.enabled: false

extraction:
  initialise: true
  max:
    batch:
      row: 100000
  filter:
    jurisdiction:
      in: ["'DIVORCE'", "'PROBATE', 'ARCHIVED'"]
      out:
        - "'AUTOTEST1'"
        - "'TEST'"
  caseTypes:
  - container: "grantofrepresentation"
    caseType: "GrantOfRepresentation"
    type: "jsonlines"
    prefix: "CCD-PROB-GOR"
    disabled: ${EXTRACTION_GRANT_REPRESENTATION_DISABLED:false}
  - container: "caveat"
    caseType: "Caveat"
    type: "jsonlines"
    prefix: "CCD-PROB-CAVEAT"
    disabled: ${EXTRACTION_CAVIAT_DISABLED:false}
  - container: "willlodgement"
    caseType: "WillLodgement"
    type: "jsonlines"
    prefix: "CCD-PROB-WL"
    disabled: ${EXTRACTION_WILLLODGEMENT_DISABLED:false}
  - container: "standingsearch"
    caseType: "StandingSearch"
    type: "jsonlines"
    prefix: "CCD-PROB-SS"
    disabled: ${EXTRACTION_STANDINGSEARCH_DISABLED:false}
  - container: "divorce"
    caseType: "DIVORCE"
    type: "jsonlines"
    prefix: "CCD-DIV"
    disabled: ${EXTRACTION_DIVORCE_DISABLED:true}
  - container: "finredmvp2"
    caseType: "FinancialRemedyMVP2"
    type: "jsonlines"
    prefix: "CCD-FINRED-MVP2"
    disabled: ${EXTRACTION_FINREDMVP2_DISABLED:false}
  - container: "finredcontested"
    caseType: "FinancialRemedyContested"
    type: "jsonlines"
    prefix: "CCD-FINRED-CONTESTED"
    disabled: ${EXTRACTION_FINREDCONTESTED_DISABLED:false}
  - container: "cmc"
    caseType: "MoneyClaimCase"
    type: "jsonlines"
    prefix: "CCD-CMC"
    disabled: ${EXTRACTION_CMC_DISABLED:false}
  - container: "asylum"
    caseType: "Asylum"
    type: "jsonlines"
    prefix: "CCD-ASYLUM"
    disabled: ${EXTRACTION_ASYLUM_DISABLED:false}
  - container: "sscs"
    caseType: "Benefit"
    type: "jsonlines"
    prefix: "CCD-SSCS"
    disabled: ${EXTRACTION_SSCS_DISABLED:false}

application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:""}

task:
  SetLastUpdateMetadata: ${TASK_SET_LAST_UPDATE:false}