job:
  image: ${IMAGE_NAME}
  keyVaults:
    "data-extractor":
      resourceGroup: data-extractor
      secrets:
        - aat-ccdro-user
        - aat-ccdro-password
        - data-extractor-connection-string
  memoryLimits: '2048Mi'
  cpuLimits: '2000m'
  ttlSecondsAfterFinished: 0
  labels:
    app.kubernetes.io/instance : data-extractor-job-001
    app.kubernetes.io/name: data-extractor-job
  environment:
    ETL_DB_URL: jdbc:postgresql://ccd-data-store-api-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com:5432/ccd_data_store
    ETL_DB_USER_FILE: data-extractor/{{ .Values.global.environment }}-ccdro-user
    ETL_DB_PASSWORD_FILE: data-extractor/{{ .Values.global.environment }}-ccdro-password
    ETL_ACCOUNT: miphasetwostorage1
    APPINSIGHTS_INSTRUMENTATIONKEY: c3043e63-3383-4add-a507-e0adf8588e4a
global:
  job:
    kind: Job
