job:
  image: ${IMAGE_NAME}
  keyVaults:
    "mi-vault":
      resourceGroup: mi-{{ .Values.global.environment }}-rg
      secrets:
        - aat-ccdro-user
        - aat-ccdro-password
        - data-extractor-connection-string
  memoryLimits: '2048Mi'
  cpuLimits: '2000m'
  kind: Job
  ttlSecondsAfterFinished: 30
  labels:
    app.kubernetes.io/instance : data-extractor-job-001
    app.kubernetes.io/name: data-extractor-job
  environment:
    ETL_DB_URL: jdbc:postgresql://ccd-data-store-api-postgres-db-{{ .Values.global.ccd_environment }}.postgres.database.azure.com:5432/ccd_data_store
    ETL_ACCOUNT: midatastg
    APPINSIGHTS_INSTRUMENTATIONKEY: c3043e63-3383-4add-a507-e0adf8588e4a
global:
  enableKeyVaults: true
  environment: "sbox"
  ccd_environment: "aat"
  usepodidentity: false
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

