mi-job:
  image: ${IMAGE_NAME}
  keyVaults:
    "mi-vault":
      resourceGroup: mi-{{ .Values.global.environment }}-rg
      secrets:
        - ccdro-user
        - ccdro-password
        - appinsights-instrumentationkey
        - data-extractor-connection-string
  memoryLimits: '2048Mi'
  cpuLimits: '2000m'
  kind: Job
  ttlSecondsAfterFinished: 30
  aadIdentityName: mi-data-extractor-job
  activeDeadlineSeconds: 600
  labels:
    app.kubernetes.io/instance : data-extractor-job-001
    app.kubernetes.io/name: data-extractor-job
  environment:
    ETL_DB_URL: jdbc:postgresql://ccd-data-store-api-postgres-db-{{ .Values.global.ccd_environment }}.postgres.database.azure.com:5432/ccd_data_store
    ETL_ACCOUNT: midataextractor{{ .Values.global.environment }}
    EXTRACTION_CASETYPES_0__CONTAINER: "test-container"
    EXTRACTION_CASETYPES_0__CASETYPE: "Caveat"
    EXTRACTION_CASETYPES_0__TYPE: "jsonlines"
    EXTRACTION_CASETYPES_0__PREFIX: "CCD-TEST"
    EXTRACTION_FILTER_JURISDICTION_IN: ["'DIVORCE'"]
    EXTRACTION_INITIALISE: false
global:
  enableKeyVaults: true
  environment: "sbox"
  ccd_environment: "aat"
  usepodidentity: true
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

