mi-job:
  image: ${IMAGE_NAME}
  environment:
    ETL_MSICLIENTID: 0a0afc36-0228-49d7-886c-77533f9621bb
    EXTRACTION_CASETYPES_0__CONTAINER: "test-container-${BUILD_VERSION}"
    EXTRACTION_CASETYPES_0__CASETYPE: "Asylum"
    EXTRACTION_CASETYPES_0__TYPE: "jsonlines"
    EXTRACTION_CASETYPES_0__PREFIX: "CCD-TEST"
    EXTRACTION_FILTER_JURISDICTION_IN: "'IA'"
    EXTRACTION_INITIALISE: false
global:
  subscriptionId: "74dacd4f-a248-45bb-a2f0-af700dc4cf68"
  environment: "stg"
