parameters:
  env: 'test'
  product: $(product)
  application.name: ''
  chart.env: 'preview'
  azure.container.registry: $(azure.container.registry)
  azure.aks.cluster: $(azure.aks.cluster)
  azure.subscription.endpoint: $(azure.subscription.endpoint)
  azure.aks.resourcegroup: $(azure.aks.resourcegroup)
  azure.prom.acr: $(azure.prom.acr)
  azure.prom.subscription.endpoint: $(azure.prom.subscription.endpoint)

stages:
- stage: BuildAndDeploy
  jobs:
    - job: EchoVariablesSBox
      pool:
        vmImage: 'Ubuntu-16.04'
      variables:
        env: ${{ parameters.env }}
      steps:
        - template: ./templates//tasks/docker-tag.yaml
        - template: ./templates/tasks/echo-variables.yaml
          parameters:
            azureContainerRegistry: ${{ parameters.azure.aks.cluster }}
            aksCluster: 'Overriden aksCluster'
    - job: EchoVariablesTest
      pool:
        vmImage: 'Ubuntu-16.04'
      variables:
          ${{ if eq(parameters.debug, 'true') }}:
            env: ${{ parameters.env }}
          
      steps:
        - template: ./templates/tasks/docker-tag.yaml

    - job: BuildAndTestApplication
      pool:
        vmImage: 'Ubuntu-16.04'
      dependsOn: EchoVariablesSBox
      # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      variables:
        aptDependencies: 'qtbase5-dev'
        env: ${{ parameters.env }}
      steps:
        - template: ./templates/tasks/build-assemble.yaml
        - template: pipeline-steps/templates/publish-tests.yaml@mi-core
        - template: ./templates/tasks/publish-artifact.yaml
        - template: ./templates/docker-build.yaml
          parameters:
            azureContainerRegistry: ${{ parameters.azure.container.registry }}
            azureSubscriptionEndpoint: ${{ parameters.azure.subscription.endpoint }}
            applicationName: ${{ parameters.application.name }}

    - job: DeployBuild
      dependsOn: BuildAndTestApplication
      condition: succeeded()
      pool:
        vmImage: 'Ubuntu-16.04'
      variables:
        env: ${{ parameters.env }}
      steps:
        - template: ./templates/helm-install-chart-job.yaml
          parameters:
            azureContainerRegistry: ${{ parameters.azure.container.registry }}
            azureSubscriptionEndpoint: ${{ parameters.azure.subscription.endpoint }}
            applicationName: ${{ parameters.application.name }}
            aksResourceGroup: ${{ parameters.azure.aks.resourcegroup }}
            aksCluster: ${{ parameters.azure.aks.cluster }}
            jobName: ${{ parameters.application.name }}
            namespace: ${{ parameters.product }}
            chartEnv: ${{ parameters.chart.env }}
        - template: ./templates/kubernetes-wait-for-job.yaml
          parameters:
            azureSubscriptionEndpoint: ${{ parameters.azure.subscription.endpoint }}
            aksResourceGroup: ${{ parameters.azure.aks.resourcegroup }}
            aksCluster: ${{ parameters.azure.aks.cluster }}
            jobName: ${{ parameters.application.name }}
            namespace: ${{ parameters.product }}
            projectName: ${{ parameters.application.name }}

    - job: PromoteBuild
      dependsOn: DeployBuild
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      pool:
        vmImage: 'Ubuntu-16.04'
      variables:
        env: ${{ parameters.env }}
      steps:
        - template: ./templates/promote-build.yaml
          parameters:
            azureContainerRegistry: ${{ parameters.azure.container.registry }}
            applicationName: ${{ parameters.application.name }}
            azureDestinyContainerRegistry: ${{ parameters.azure.prom.acr }}
            azureProdSubscription: ${{ parameters.azure.prom.subscription.endpoint }}
